language: python
python:
- '3.4'
cache: pip
branches:
  only:
  - src
install: pip install -r requirements.txt
env:
  global:
  - secure: FnJj33rSpUK6eBDleF7UqpPpNxo/MsAwTsG9U8ZfHAIzxCGtU1ASUGp1nldjhKG76Z5pcAI9ZsCvDOuH52h0RZoJJDvGddsHnmnGhp1gRYuuQqolfdvYEY9HvW7+/T4ycgXJwHlq4C7+q4PXN2IEptuBIcSx5bpv8b2ChCkuWSJA37C6wE9grVw9StrOYkl6oavfAr0R67+PkvtZLcbTG2PK64ATbJ2eOTdlXSb6F0JtKNYDNDarhccjJE0t+b4UJIbKquvHT2XIMeHijYNpwxl2LLNDkc74bYrJQqVDcjsbrRhFKhDrzVBXyc3FRAhArxy+lIcYqydRYGXTQnZzRB5Won8LND/BbQfpG0onWnCe6/EfuxjYBuNKvwpPNSf4rdeCmlwr+B5o1g+reuFLM3vN5jGJRyIU/rX14oliktEJBnf/J3WiABnSzyIcijoxnqBgKYIqqQZs+0F9WquE7Iiub/RhL+VCECIOfwx9b+hQqO0UgYrX1O8krjsGTRZT1talNazvM7t4p66v0y4XHJnHzs2ghRalfbFu1yGsxxR3g937qxC8pYmbP8J6EC/9IvDdW4ZeZBJWUz9OMkXEH6KtvZ2hOPCH1oQwpKLamvEpREeQODKMKRuSLBv7ZkmMo5nOdNbnBPnsRZa+aYitLXLidVpbcLWp0KKoamUptNM=
  - secure: ji5+NMxNVdEmQr2/50OXJrTwh5TZ7dCI1PbGc5QhrKzyA02fs6g006+vbdk5fIx0NcbkS/MB8x5VOr1AwweYerqtW4BDtjWHj4mZStZQZCxxBf3NUTQDF8Q6GXyFN7fNARq0Jkf2FtDLEYaxM/78rMYZJEZ8E6UuX2W2Yhq9QmeCq3kR3cRoNWiDpIRyooxxPCsJAwCTuDj2PJNvfFIy4UxHULRIRYNRMFb2ZhrOb5qjPir+xeFOGjJqiigzf4CTixNeQFQvMmWVhr15+Nz6AZbCUlvg4a0jKmZyXcOFY7LMPIi7hfSLG1gAij0oMm3wVFaxir1PAoy+V010VqxWaSV8uviJmf8tPwWZ0Lwid2n13n26oIDqZV8jLohvIpvDmjk5sn/HIvF4V/hOCtY7Hya2tG9OamfFLRIvhubqTJ/TaTetcIaz+QhMWUdDlBluUSi0srlKQn6UBaxWbg98RhOuTKX5DyiV0vXVJL0PaL2d0sMqzBDQThBI0A1QVjGqgcPsTwWHUuufdFM1Al/GpJUmoxnOPkJQX+YmP12OAz/U0ZdrD5LKUO5LHp+UdkdDUgKb6O5PiWbLkKZHS2/lJXmLDPUwBxnj4jy4k3Q/tiCLmB5iVwqoPnn/21NWZ+vthT6B472CftVpEU1hgs0FsjdG2Kzzz61MH+CQFP70a7E=
script:
- git config --global user.email "mail@rohitja.in"
- git config --global user.name "Travis for Rohit Jain"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git checkout src
- pelican content -s publishconf.py -t pelican-themes/Flex
- git add .
- git commit -m "travis regen merge"
- git fetch origin master:master
- ghp-import output -b master
- git checkout master
- git push origin master
